/*
  Template configurations organized by CATEGORY (relationship stage).
  Categories: crush, new-couple, long-term, y2k
*/

// ============ CRUSH / Дурлал ============
const CRUSH_TEMPLATES = [
  {
    id: 'crush-shy',
    category: 'crush',
    name: 'Ичимхий зөрөлт 🦋',
    desc: 'Зоригтой алхам хийх цаг боллоо',
    preview: '😍🦋',
    theme: 'theme-crush-shy',
    colors: {
      '--t-primary': '#ff6b9d',
      '--t-secondary': '#ff4081',
      '--t-accent': '#f093fb',
      '--t-accent2': '#f5576c',
      '--t-soft': '#ff9a9e',
      '--t-light': '#ffd1dc',
      '--t-bg': '#120018',
      '--t-bg2': '#1e0028',
      '--t-glass': 'rgba(255, 107, 157, 0.05)',
      '--t-glass-border': 'rgba(255, 107, 157, 0.15)',
    },
    character: 'butterfly',
    welcomeEmoji: '🦋',
    welcomeTitle: 'Чамд нэг юм хэлмээр байна... 💕',
    welcomeSubtitle: 'Зүрхнийхээ үгийг сонсоорой\nЭнэ урилга чамд 💌',
    questionText: 'Энэ Valentine\'s Day-д миний хамт гарах уу? Чамтай хамт байхыг маш их хүсч байна... 🥺💕',
    loveLetter: {
      enabled: true,
      title: 'Миний зүрхний захидал 💌',
      content: 'Чамайг анх харсан тэр мөчөөс хойш миний зүрхний цохилт өөрчлөгдсөн... Чамтай ярих болгондоо эрвээхэй нисдэг. Энэ Valentine\'s Day-д зориг гаргаад хэлмээр байна — чи миний хамгийн онцгой хүн 💕',
    },
    steps: [
      {
        emoji: '☕', title: 'Хаана уулзах вэ?', key: 'place', type: 'grid', multiSelect: false,
        options: [
          { emoji: '☕', name: 'Кафе', desc: 'Тайван яриа өрнүүлье', value: 'Кафе' },
          { emoji: '🌸', name: 'Парк', desc: 'Алхаж ярилцъя', value: 'Парк' },
          { emoji: '🎬', name: 'Кино', desc: 'Хамтдаа кино үзье', value: 'Кино' },
          { emoji: '🍦', name: 'Зайрмаг', desc: 'Зайрмаг идэнгээ', value: 'Зайрмаг' },
          { emoji: '📚', name: 'Номын дэлгүүр', desc: 'Номын дэлгүүр хэсье', value: 'Номын дэлгүүр' },
          { emoji: '🎡', name: 'Парк зугаалга', desc: 'Зугаалгын газар', value: 'Зугаалгын парк' },
        ],
      },
      {
        emoji: '💬', title: 'Юу хийх вэ?', key: 'activity', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🗣️', name: 'Ярилцах', value: 'Ярилцана' },
          { emoji: '📸', name: 'Зураг авах', value: 'Зураг авна' },
          { emoji: '🎶', name: 'Хөгжим сонсох', value: 'Хөгжим сонсоно' },
          { emoji: '🍰', name: 'Амттан идэх', value: 'Амттан идэнэ' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглоом тоглоно' },
          { emoji: '🚶', name: 'Алхах', value: 'Хамтдаа алхана' },
        ],
      },
      {
        emoji: '⏰', title: 'Хэдэн цагт?', key: 'time', type: 'time', multiSelect: false,
        options: [
          { label: '☀️ 13:00', value: '13:00' },
          { label: '🌤️ 15:00', value: '15:00' },
          { label: '🌅 17:00', value: '17:00' },
          { label: '🌙 19:00', value: '19:00' },
        ],
      },
      {
        emoji: '👗', title: 'Хувцасны стиль', key: 'outfit', type: 'grid', multiSelect: false,
        options: [
          { emoji: '✨', name: 'Гоёхон', value: 'Гоёхон' },
          { emoji: '👕', name: 'Энгийн', value: 'Энгийн' },
          { emoji: '🎀', name: 'Cute', value: 'Cute' },
          { emoji: '🤷', name: 'Чи шийд 😉', value: 'Чи шийдээрэй' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '🦋', date: 'Анхны мөч', caption: 'Чамайг анх харсан тэр мөч... ✨' },
      { type: 'image', src: '', placeholder: '💕', date: 'Зүрхний цохилт', caption: 'Зүрх минь түргэсдэг... 💓' },
      { type: 'image', src: '', placeholder: '😊', date: 'Инээмсэглэл', caption: 'Чиний инээмсэглэл намайг аз жаргалтай болгодог 🌸' },
      { type: 'image', src: '', placeholder: '📱', date: 'Мессеж', caption: 'Чатлах бүрдээ инээмсэглэдэг 😊' },
    ],
    quotes: [
      'Чамайг анх харсан тэр мөчөөс зүрх минь өөр хүнийхээ нэрээр цохилдог 💘',
      'Чиний инээмсэглэл бол миний өдрийн хамгийн гоё мөч 🦋',
      'Зоригтой байх нэг шалтгаан байна — чи 💕',
      'Crush гэдэг энэ мэдрэмж шиг гайхалтай зүйл байхгүй 😍',
    ],
  },
  {
    id: 'crush-bold',
    category: 'crush',
    name: 'Зоригтой мэдэгдэл 🔥',
    desc: 'Шулуухан, зоригтой хэлбэрээр',
    preview: '🔥💘',
    theme: 'theme-crush-bold',
    colors: {
      '--t-primary': '#ff4757',
      '--t-secondary': '#ff3838',
      '--t-accent': '#ff6348',
      '--t-accent2': '#e84393',
      '--t-soft': '#fab1a0',
      '--t-light': '#ffeaa7',
      '--t-bg': '#1a0008',
      '--t-bg2': '#2d0012',
      '--t-glass': 'rgba(255, 71, 87, 0.06)',
      '--t-glass-border': 'rgba(255, 71, 87, 0.18)',
    },
    character: 'fire',
    welcomeEmoji: '🔥',
    welcomeTitle: 'Чамд шууд хэлье 🔥',
    welcomeSubtitle: 'Нууцалж байгаад олдсангүй\nОдоо шулуухан хэлнэ 💪',
    questionText: 'Чи надад таалагддаг. Valentine\'s Day-д хамтдаа байх уу? Миний хамт 🔥',
    loveLetter: {
      enabled: true,
      title: 'Зүрхнээсээ хэлэх нь 🔥',
      content: 'Удаан бодож байгаад олддоггүй. Шулуухан хэлье — чи надад үнэхээр таалагддаг. Өдөр бүр чам тухай бодож байгаа. Энэ Valentine\'s Day-д хоёулаа гоё цаг өнгөрөөхгүй юу? 🔥❤️',
    },
    steps: [
      {
        emoji: '🔥', title: 'Хаана болзоо хийх вэ?', key: 'place', type: 'grid', multiSelect: false,
        options: [
          { emoji: '🍽️', name: 'Ресторан', desc: 'Гоё газар хоол идъе', value: 'Ресторан' },
          { emoji: '🎬', name: 'Кино', desc: 'Сонирхолтой кино', value: 'Кино' },
          { emoji: '🌃', name: 'Шөнийн хот', desc: 'Хотоор гарцгааё', value: 'Шөнийн хот' },
          { emoji: '🎤', name: 'Караоке', desc: 'Хамтдаа дуулъя', value: 'Караоке' },
          { emoji: '🎡', name: 'Adventure', desc: 'Адал явдалтай', value: 'Adventure' },
          { emoji: '☕', name: 'Кафе', desc: 'Тайван ярьцгая', value: 'Кафе' },
        ],
      },
      {
        emoji: '⚡', title: 'Юу хийх вэ?', key: 'activity', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🍕', name: 'Хоол идэх', value: 'Хоол идэнгээ' },
          { emoji: '🎤', name: 'Караоке', value: 'Караоке дуулъя' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглоом' },
          { emoji: '🌃', name: 'Зугаалах', value: 'Зугаалъя' },
          { emoji: '📸', name: 'Зураг авах', value: 'Зураг авъя' },
          { emoji: '💃', name: 'Бүжиглэх', value: 'Бүжиглэнгээ' },
        ],
      },
      {
        emoji: '⏰', title: 'Хэдэн цагт?', key: 'time', type: 'time', multiSelect: false,
        options: [
          { label: '🌅 17:00', value: '17:00' },
          { label: '🌆 18:00', value: '18:00' },
          { label: '🌙 19:00', value: '19:00' },
          { label: '✨ 20:00', value: '20:00' },
          { label: '🌃 21:00', value: '21:00' },
        ],
      },
      {
        emoji: '👗', title: 'Яаж хувцаслах вэ?', key: 'outfit', type: 'grid', multiSelect: false,
        options: [
          { emoji: '🔥', name: 'Гоёмсог', value: 'Гоёмсог' },
          { emoji: '😎', name: 'Cool стиль', value: 'Cool стиль' },
          { emoji: '👫', name: 'Хос стиль', value: 'Хос стиль' },
          { emoji: '🤫', name: 'Сюрприз', value: 'Сюрприз' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '🔥', date: 'First sight', caption: 'Анх чамайг харсан тэр мөч 🔥' },
      { type: 'image', src: '', placeholder: '😊', date: 'Хамтын мөч', caption: 'Инээмсэглэл бүр зүрхийг шатаадаг ❤️‍🔥' },
      { type: 'image', src: '', placeholder: '📱', date: 'Chat', caption: 'Бичсэн мессеж бүрт зүрх дүүрэн 💬' },
      { type: 'image', src: '', placeholder: '⭐', date: 'Ирээдүй', caption: 'Ирээдүйд хамтдаа... 🌟' },
    ],
    quotes: [
      'Чи зүрхийг минь шатаадаг 🔥',
      'Юу ч нуухгүй — чамд дурлаж байна ❤️‍🔥',
      'Life is short, чамтай хамт байх хүсэл урт 💪',
      'Зоригтой байх шалтгаан — чи 🔥',
    ],
  },
]

// ============ ШИНЭ ХОС ============
const NEW_COUPLE_TEMPLATES = [
  {
    id: 'spark',
    category: 'new-couple',
    name: 'The Spark ✨',
    desc: 'Invitation for new beginnings',
    preview: '✨💞',
    theme: 'theme-spark',
    customizer: 'spark',
    colors: {
      '--t-primary': '#ff6bb5',
      '--t-secondary': '#a855f7',
      '--t-accent': '#ffd1dc',
      '--t-accent2': '#ff8fab',
      '--t-soft': '#ffc8dd',
      '--t-light': '#ffebf0',
      '--t-bg': '#120018',
      '--t-bg2': '#1a0025',
      '--t-glass': 'rgba(255, 255, 255, 0.05)',
      '--t-glass-border': 'rgba(255, 107, 181, 0.16)',
    },
    character: 'cat',
    welcomeEmoji: '✨',
    welcomeTitle: 'The Spark ✨',
    welcomeSubtitle: 'Invitation for new beginnings\nLet\'s make it special 💖',
    questionText: 'Be my Valentine? 💖',
    loveLetter: {
      enabled: true,
      title: 'For Our New Beginning ✨',
      content: 'Чамтай хамт эхэлсэн энэ шинэ түүх миний хамгийн гоё мэдрэмж. Энэ Valentine\'s Day-д бид хоёрын "эхлэл" хамгийн романтик дурсамж болгоцгооё 💖',
    },
    steps: [
      {
        emoji: '📍',
        title: 'Хаана уулзах вэ?',
        key: 'place',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '☕', name: 'Кафе', desc: 'Тайван яриа', value: 'Кафе' },
          { emoji: '🎬', name: 'Кино', desc: 'Хамтдаа кино', value: 'Кино' },
          { emoji: '🌸', name: 'Парк', desc: 'Алхаж ярилцъя', value: 'Парк' },
          { emoji: '🍰', name: 'Dessert', desc: 'Амттан', value: 'Dessert' },
          { emoji: '🍽️', name: 'Ресторан', desc: 'Оройн хоол', value: 'Ресторан' },
          { emoji: '🏠', name: 'Гэрийн date', desc: 'Cozy', value: 'Гэрийн date' },
        ],
      },
      {
        emoji: '🎯',
        title: 'Юу хийх вэ?',
        key: 'activity',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🗣️', name: 'Ярилцах', value: 'Ярилцана' },
          { emoji: '📸', name: 'Зураг авах', value: 'Зураг авна' },
          { emoji: '🎶', name: 'Дуу сонсох', value: 'Дуу сонсоно' },
          { emoji: '🍫', name: 'Амттан', value: 'Амттан иднэ' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглоом тоглоно' },
          { emoji: '🚶', name: 'Алхах', value: 'Хамтдаа алхана' },
        ],
      },
      {
        emoji: '⏰',
        title: 'Хэдэн цагт?',
        key: 'time',
        type: 'time',
        multiSelect: false,
        options: [
          { label: '☀️ 14:00', value: '14:00' },
          { label: '🌅 17:00', value: '17:00' },
          { label: '🌙 19:00', value: '19:00' },
          { label: '✨ 20:00', value: '20:00' },
        ],
      },
      {
        emoji: '👗',
        title: 'Хувцасны стиль',
        key: 'outfit',
        type: 'grid',
        multiSelect: false,
        options: [
          { emoji: '🎀', name: 'Cute', value: 'Cute' },
          { emoji: '✨', name: 'Гялалзсан', value: 'Гялалзсан' },
          { emoji: '👫', name: 'Matching', value: 'Matching' },
          { emoji: '🤍', name: 'Энгийн', value: 'Энгийн' },
        ],
      },
      {
        emoji: '🎁',
        title: 'Бэлэг',
        key: 'gift',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🌹', name: 'Цэцэг', value: 'Цэцэг' },
          { emoji: '🍫', name: 'Шоколад', value: 'Шоколад' },
          { emoji: '💌', name: 'Захидал', value: 'Захидал' },
          { emoji: '🧸', name: 'Тоглоом', value: 'Тоглоом' },
          { emoji: '🎀', name: 'Accessory', value: 'Accessory' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '✨', date: 'Эхлэл', caption: 'Бидний шинэ эхлэл ✨' },
      { type: 'image', src: '', placeholder: '💞', date: 'Инээмсэглэл', caption: 'Чиний инээмсэглэл 💖' },
      { type: 'image', src: '', placeholder: '📸', date: 'Дурсамж', caption: 'Хамтдаа зураг авъя 📸' },
      { type: 'image', src: '', placeholder: '🌸', date: 'Мөч', caption: 'Жижигхэн мөртлөө онцгой мөчүүд 🌸' },
    ],
    quotes: [
      'New beginnings, same butterflies ✨',
      'Чи бол миний хамгийн гоё эхлэл 💖',
      'Энэ Valentine бидний хамгийн анхны онцгой дурсамж 💞',
      'Let\'s make some memories ✨',
    ],
  },
  {
    id: 'new-sweet',
    category: 'new-couple',
    name: 'Чихэрлэг эхлэл 🍬',
    desc: 'Шинэ хайрын сайхан мөчүүд',
    preview: '🥰🍬',
    theme: 'theme-new-sweet',
    colors: {
      '--t-primary': '#ff8fab',
      '--t-secondary': '#fb6f92',
      '--t-accent': '#f093fb',
      '--t-accent2': '#a855f7',
      '--t-soft': '#ffc8dd',
      '--t-light': '#ffebf0',
      '--t-bg': '#150010',
      '--t-bg2': '#200018',
      '--t-glass': 'rgba(255, 143, 171, 0.05)',
      '--t-glass-border': 'rgba(255, 143, 171, 0.15)',
    },
    character: 'cat',
    welcomeEmoji: '🍬',
    welcomeTitle: 'Миний чихэрлэг хайр 🍬',
    welcomeSubtitle: 'Бидний хамтын анхны Valentine\'s Day\nОнцгой болгоцгооё 💕',
    questionText: 'Анхны Valentine\'s Day маань гоё байх нь ээ! Хамтдаа байх уу бэйби? 🥰',
    loveLetter: {
      enabled: true,
      title: 'Миний амттайхан 💌',
      content: 'Чамтай үерхээд хэдхэн сар болсон ч өдөр бүр шинэ мэдрэмж нээдэг. Чи бол миний хайрын хамгийн амттай хэсэг. Анхны Valentine\'s Day маань мартагдашгүй байг! 🍬💕',
    },
    steps: [
      {
        emoji: '🧁', title: 'Хаана date хийх вэ?', key: 'place', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🍰', name: 'Bakery & Кафе', desc: 'Амттай зүйл идье', value: 'Bakery & Кафе' },
          { emoji: '🍽️', name: 'Ресторан', desc: 'Романтик оройн хоол', value: 'Ресторан' },
          { emoji: '🎬', name: 'Кино', desc: 'Романтик кино', value: 'Кино' },
          { emoji: '🏠', name: 'Гэрийн date', desc: 'Netflix & chill', value: 'Гэрийн date' },
          { emoji: '🛍️', name: 'Shopping', desc: 'Хамтдаа дэлгүүр', value: 'Shopping' },
          { emoji: '🎡', name: 'Парк', desc: 'Зугаалгын газар', value: 'Зугаалгын парк' },
        ],
      },
      {
        emoji: '💕', title: 'Юу хийх вэ?', key: 'activity', type: 'grid', multiSelect: true,
        options: [
          { emoji: '📸', name: 'Couple photo', value: 'Couple зураг авна' },
          { emoji: '🧁', name: 'Bake хийх', value: 'Хамтдаа bake хийнэ' },
          { emoji: '🎥', name: 'Кино үзэх', value: 'Кино үзнэ' },
          { emoji: '💃', name: 'Бүжиглэх', value: 'Бүжиглэнэ' },
          { emoji: '🎤', name: 'Караоке', value: 'Караоке дуулна' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглоом тоглоно' },
        ],
      },
      {
        emoji: '⏰', title: 'Хэдэн цагт уулзах вэ?', key: 'time', type: 'time', multiSelect: false,
        options: [
          { label: '🌸 12:00', value: '12:00' },
          { label: '☀️ 14:00', value: '14:00' },
          { label: '🌅 17:00', value: '17:00' },
          { label: '🌙 19:00', value: '19:00' },
          { label: '✨ 20:00', value: '20:00' },
        ],
      },
      {
        emoji: '👗', title: 'Хувцасны стиль', key: 'outfit', type: 'grid', multiSelect: false,
        options: [
          { emoji: '🌸', name: 'Cute & Pink', value: 'Cute & Pink' },
          { emoji: '👫', name: 'Matching outfit', value: 'Matching outfit' },
          { emoji: '✨', name: 'Гялалзсан', value: 'Гялалзсан' },
          { emoji: '🎀', name: 'Сюрприз!', value: 'Сюрприз' },
        ],
      },
      {
        emoji: '🎁', title: 'Бэлэг юу авах вэ?', key: 'gift', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🌹', name: 'Цэцэг', value: 'Цэцэг' },
          { emoji: '🍫', name: 'Шоколад', value: 'Шоколад' },
          { emoji: '🧸', name: 'Тоглоом', value: 'Тоглоом' },
          { emoji: '💌', name: 'Захидал', value: 'Захидал' },
          { emoji: '📸', name: 'Couple зураг', value: 'Couple зураг' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз бэлэг' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '🥰', date: 'Эхний date', caption: 'Анхны болзоо маш сайхан байсан 💕' },
      { type: 'image', src: '', placeholder: '🤳', date: 'Selfie', caption: 'Анхны хос зураг 📸' },
      { type: 'image', src: '', placeholder: '💕', date: 'Хамтын мөч', caption: 'Чамтай хамт байхад сэтгэл жаргалтай 🥰' },
      { type: 'image', src: '', placeholder: '🎉', date: 'Тэмдэглэл', caption: 'Бидний анхны онцгой мөч ✨' },
    ],
    quotes: [
      'Чамтай нэг нэг өдрийг илүүд үзнэ хэн нэгнийг бүхэлд нь 💕',
      'Шинэ хайр шиг сайхан зүйл байхгүй 🥰',
      'Чамтай хамт байх цаг бүр шинэ адал явдал 🍬',
      'Миний зүрхний эзэн чи л гэдгийг чи мэдэх үү? 💖',
    ],
  },
]

// ============ УДААН ХОС (existing) ============
const LONG_TERM_TEMPLATES = [
  {
    id: 'classic',
    category: 'long-term',
    name: 'Сонгодог Романтик 💕',
    desc: 'Уламжлалт ягаан, зүрхэн дизайн',
    preview: '🐻💝',
    theme: 'theme-classic',
    colors: {
      '--t-primary': '#ff6b9d',
      '--t-secondary': '#ff4081',
      '--t-accent': '#c471ed',
      '--t-accent2': '#7c4dff',
      '--t-soft': '#ff9a9e',
      '--t-light': '#ffd1dc',
      '--t-bg': '#0d0015',
      '--t-bg2': '#1a0025',
      '--t-glass': 'rgba(255, 255, 255, 0.04)',
      '--t-glass-border': 'rgba(255, 100, 150, 0.15)',
    },
    character: 'bear',
    welcomeEmoji: '💝',
    welcomeTitle: 'Happy Valentine\'s Day 💕',
    welcomeSubtitle: 'Хамгийн хайртай хүндээ зориулсан\nтусгай урилга ❤️',
    questionText: '2.14-нд хамтдаа гоё байж болон шдээ Чи надтай гал халуун шөнийг өнгөрөөх үү? 🥺',
    loveLetter: {
      enabled: true,
      title: 'Хайр минь 💕',
      content: 'Олон жил хамт байсан ч чамд дурлах сэтгэл маань анхны өдрийнхөө адил хүчтэй. Чамтай хамт байсан жил бүр миний амьдралын хамгийн гоё хуудас. Хайр минь, энэ Valentine\'s Day маань ч гэсэн онцгой байг 💝',
    },
    steps: [
      {
        emoji: '📍',
        title: 'Хаана хийх вэ?',
        key: 'place',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🍽️', name: 'Ресторан', desc: 'Романтик оройн хоол', value: 'Ресторан' },
          { emoji: '☕', name: 'Кафе', desc: 'Дулаахан уур амьсгал', value: 'Кафе' },
          { emoji: '🎬', name: 'Кино театр', desc: 'Хамтдаа кино үзье', value: 'Кино театр' },
          { emoji: '🏠', name: 'Гэрээр', desc: 'Хамтдаа хоол хийе', value: 'Гэрээр' },
          { emoji: '🌃', name: 'Шөнийн хот', desc: 'Хотоор зугаалъя', value: 'Шөнийн хот' },
          { emoji: '🏔️', name: 'Байгаль', desc: 'Байгалийн үзэсгэлэн', value: 'Байгаль' },
        ],
      },
      {
        emoji: '🎯',
        title: 'Яаж хийх вэ?',
        key: 'activity',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🍕', name: 'Хоол идэх', value: 'Хоол идэнгээ' },
          { emoji: '🚶‍♂️', name: 'Алхах', value: 'Алхангаа' },
          { emoji: '🎥', name: 'Кино үзэх', value: 'Кино үзэнгээ' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглонгоо' },
          { emoji: '💃', name: 'Бүжиглэх', value: 'Бүжиглэнгээ' },
          { emoji: '🎤', name: 'Караоке', value: 'Караоке хийж' },
        ],
      },
      {
        emoji: '⏰',
        title: 'Хэдэн цаг хийх вэ?',
        key: 'time',
        type: 'time',
        multiSelect: false,
        options: [
          { label: '🌤️ 12:00', value: '12:00' },
          { label: '☀️ 14:00', value: '14:00' },
          { label: '🌅 17:00', value: '17:00' },
          { label: '🌙 19:00', value: '19:00' },
          { label: '✨ 20:00', value: '20:00' },
          { label: '🌃 21:00', value: '21:00' },
        ],
      },
      {
        emoji: '👗',
        title: 'Хувцасны хэв маяг',
        key: 'outfit',
        type: 'grid',
        multiSelect: false,
        options: [
          { emoji: '👔', name: 'Гоёмсог', value: 'Гоёмсог' },
          { emoji: '👕', name: 'Энгийн тохилог', value: 'Энгийн тохилог' },
          { emoji: '👫', name: 'Хос хувцас', value: 'Хос хувцас' },
          { emoji: '🎁', name: 'Сюрприз!', value: 'Сюрприз' },
        ],
      },
      {
        emoji: '🎁',
        title: 'Бэлэг юу авах вэ?',
        key: 'gift',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🌹', name: 'Цэцэг', value: 'Цэцэг' },
          { emoji: '🍫', name: 'Шоколад', value: 'Шоколад' },
          { emoji: '💍', name: 'Зүүлт', value: 'Зүүлт' },
          { emoji: '🧸', name: 'Тоглоом баавгай', value: 'Тоглоом баавгай' },
          { emoji: '💌', name: 'Захидал', value: 'Захидал' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз бэлэг' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '📸', date: 'Эхний уулзалт', caption: 'Анх уулзсан тэр мөч... ✨' },
      { type: 'image', src: '', placeholder: '🎂', date: 'Төрсөн өдөр', caption: 'Чамтай хамт тэмдэглэсэн анхны төрсөн өдөр 😊🎉' },
      { type: 'video', src: '', placeholder: '🎥', date: 'Дурсамж', caption: 'Хамтдаа хийж байсан тэр мөч 😊' },
      { type: 'image', src: '', placeholder: '🌅', date: 'Аялал', caption: 'Нар жаргахыг хамтдаа харцгааья  🌇' },
      { type: 'image', src: '', placeholder: '💕', date: 'Онцгой мөч', caption: 'Чамтай байх мөч бүр онцгой 💖' },
      { type: 'video', src: '', placeholder: '🎬', date: 'Бидний видео', caption: 'Бид хоёрын мартагдашгүй мөч 🥰' },
    ],
    quotes: [
      'Чамтай хамт байх мөч бүр миний амьдралын хамгийн үнэт мөчүүд 💕',
      'Хайр гэдэг чамтай хамт амьдрах мөрөөдөл 🌙',
      'Чи бол миний бүх зүйл 💝',
      'Зүрхний цохилт бүр чиний нэрээр цохилдог ❤️',
    ],
  },

  {
    id: 'starry',
    category: 'long-term',
    name: 'Одот Шөнө 🌙',
    desc: 'Шөнийн тэнгэр, од, сар',
    preview: '🌙⭐',
    theme: 'theme-starry',
    colors: {
      '--t-primary': '#7eb8da',
      '--t-secondary': '#5b9bd5',
      '--t-accent': '#ffd700',
      '--t-accent2': '#b8860b',
      '--t-soft': '#a3c9e2',
      '--t-light': '#e6f0fa',
      '--t-bg': '#070b1a',
      '--t-bg2': '#0f1630',
      '--t-glass': 'rgba(120, 160, 220, 0.06)',
      '--t-glass-border': 'rgba(120, 160, 220, 0.18)',
    },
    character: 'moon',
    welcomeEmoji: '🌙',
    welcomeTitle: 'Одот шөнийн урилга ⭐',
    welcomeSubtitle: 'Мянга мянган одны дундаас\nчамайг олсон миний аз ✨',
    questionText: 'Энэ Valentine\'s Day-д одтой шөнийг хамтдаа өнгөрөөх үү? 🌙',
    loveLetter: {
      enabled: true,
      title: 'Одтой шөнийн захидал 🌙',
      content: 'Тэнгэрт мянган од бялхаж байвч чамаас өөр од миний нүдэнд харагддаггүй. Бид хамт одтой шөнийг тоолсон жилүүд бол миний хамгийн гоё дурсамж. Хайр минь, энэ шөнө ч мөн чамд зориулав ⭐💙',
    },
    steps: [
      {
        emoji: '🌃',
        title: 'Хаана уулзах вэ?',
        key: 'place',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🌉', name: 'Гүүрэн дээр', desc: 'Одтой шөнө, гоё view', value: 'Гүүрэн дээр' },
          { emoji: '🍽️', name: 'Rooftop ресторан', desc: 'Дээвэр дээрх оройн хоол', value: 'Rooftop ресторан' },
          { emoji: '🏕️', name: 'Гадаа camping', desc: 'Одтой тэнгэрийн доор', value: 'Camping' },
          { emoji: '🏠', name: 'Гэрээр', desc: 'Дулаахан гэрт хамтдаа', value: 'Гэрээр' },
          { emoji: '🌳', name: 'Парк', desc: 'Шөнийн паркаар алхъя', value: 'Парк' },
          { emoji: '🚗', name: 'Drive', desc: 'Шөнийн drive хийе', value: 'Drive' },
        ],
      },
      {
        emoji: '✨',
        title: 'Юу хийх вэ?',
        key: 'activity',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🔭', name: 'Од харах', value: 'Од харанаа' },
          { emoji: '🕯️', name: 'Лааны гэрэл', value: 'Лааны гэрэлд' },
          { emoji: '🎶', name: 'Хөгжим сонсох', value: 'Хөгжим сонсоно' },
          { emoji: '🍷', name: 'Wine уух', value: 'Wine ууна' },
          { emoji: '🌌', name: 'Зураг авах', value: 'Зураг авна' },
          { emoji: '💫', name: 'Wish хийх', value: 'Wish хийнэ' },
        ],
      },
      {
        emoji: '🕐',
        title: 'Хэдэн цагт?',
        key: 'time',
        type: 'time',
        multiSelect: false,
        options: [
          { label: '🌅 18:00', value: '18:00' },
          { label: '🌆 19:00', value: '19:00' },
          { label: '🌙 20:00', value: '20:00' },
          { label: '✨ 21:00', value: '21:00' },
          { label: '🌌 22:00', value: '22:00' },
          { label: '🌃 23:00', value: '23:00' },
        ],
      },
      {
        emoji: '🧥',
        title: 'Хувцасны стиль',
        key: 'outfit',
        type: 'grid',
        multiSelect: false,
        options: [
          { emoji: '🖤', name: 'All Black', value: 'All Black' },
          { emoji: '✨', name: 'Гялалзсан', value: 'Гялалзсан' },
          { emoji: '🧣', name: 'Дулаахан cozy', value: 'Дулаахан cozy' },
          { emoji: '🌟', name: 'Сюрприз!', value: 'Сюрприз' },
        ],
      },
      {
        emoji: '🎁',
        title: 'Бэлгийн санаа',
        key: 'gift',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '⭐', name: 'Одны зураг', value: 'Одны зураг' },
          { emoji: '🌹', name: 'Цэцэг', value: 'Цэцэг' },
          { emoji: '📓', name: 'Дурсамжын ном', value: 'Дурсамжын ном' },
          { emoji: '🎵', name: 'Playlist', value: 'Playlist' },
          { emoji: '💫', name: 'Зүүлт', value: 'Зүүлт' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз бэлэг' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '🌙', date: 'Эхний шөнө', caption: 'Хамтдаа одтой тэнгэр харсан шөнө ✨' },
      { type: 'image', src: '', placeholder: '⭐', date: 'Онцгой мөч', caption: 'Чи бол миний од 🌟' },
      { type: 'video', src: '', placeholder: '🎥', date: 'Дурсамж', caption: 'Бидний хамтын мөчүүд 🌙' },
      { type: 'image', src: '', placeholder: '🌌', date: 'Аялал', caption: 'Шөнийн тэнгэрийн доор хамтдаа 💫' },
      { type: 'image', src: '', placeholder: '💫', date: 'Wish', caption: 'Одонд хүсэл тавьсан тэр шөнө 🌠' },
      { type: 'video', src: '', placeholder: '🎬', date: 'Бидний видео', caption: 'Together under the stars 🥰' },
    ],
    quotes: [
      'Тэнгэрт мянган од байвч чи бол миний цорын ганц од ⭐',
      'Шөнийн тэнгэр доор чамтай хамт байхаас илүү зүйл байхгүй 🌙',
      'Чи бол миний шөнийн гэрэл, миний сар 🌟',
      'Одод унахдаа хүслээ биелүүлдэг, чи бол миний биелсэн хүсэл 💫',
    ],
  },

  {
    id: 'candy',
    category: 'long-term',
    name: 'Чихэрлэг Хайр 🍬',
    desc: 'Pastel, kawaii, cute стиль',
    preview: '🐱🍭',
    theme: 'theme-candy',
    colors: {
      '--t-primary': '#ff8fab',
      '--t-secondary': '#fb6f92',
      '--t-accent': '#a855f7',
      '--t-accent2': '#06d6a0',
      '--t-soft': '#ffc8dd',
      '--t-light': '#ffebf0',
      '--t-bg': '#1a0a1e',
      '--t-bg2': '#230f28',
      '--t-glass': 'rgba(255, 143, 171, 0.06)',
      '--t-glass-border': 'rgba(255, 143, 171, 0.18)',
    },
    character: 'cat',
    welcomeEmoji: '🍬',
    welcomeTitle: 'Sweet Valentine 🍭',
    welcomeSubtitle: 'Амттай хайрын урилга\nЧамд зориулав 🧁',
    questionText: 'Valentine\'s Day-д хамтдаа амтархах уу? Чи миний чихэрлэг хайр! 🍬🥺',
    loveLetter: {
      enabled: true,
      title: 'Миний чихэрлэг хайр 🍬',
      content: 'Чамтай хамт байх бүр амьдрал бялуу шиг амттай. Өдөр бүр чамтай хамт байхдаа шоколад шиг аз жаргалтай байдаг. Чи бол миний хамгийн гоё амт 🧁💕',
    },
    steps: [
      {
        emoji: '🧁',
        title: 'Хаана амтархах вэ?',
        key: 'place',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🍰', name: 'Bakery', desc: 'Бялуу амтлая', value: 'Bakery' },
          { emoji: '🍦', name: 'Ice cream', desc: 'Зайрмаг идъе', value: 'Ice cream' },
          { emoji: '🧋', name: 'Bubble tea', desc: 'Bubble tea ууя', value: 'Bubble tea' },
          { emoji: '🏠', name: 'Гэрээр', desc: 'Хамтдаа bake хийе', value: 'Гэрээр' },
          { emoji: '🎡', name: 'Парк', desc: 'Зугаалгын парк', value: 'Зугаалгын парк' },
          { emoji: '🛍️', name: 'Shopping', desc: 'Дэлгүүр хэсье', value: 'Shopping' },
        ],
      },
      {
        emoji: '🎀',
        title: 'Юу хийх вэ?',
        key: 'activity',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🧁', name: 'Bake хийх', value: 'Bake хийнэ' },
          { emoji: '🎨', name: 'Зурах', value: 'Хамтдаа зурна' },
          { emoji: '📸', name: 'Photoshoot', value: 'Photoshoot' },
          { emoji: '🎮', name: 'Тоглоом', value: 'Тоглонгоо' },
          { emoji: '🎤', name: 'Караоке', value: 'Караоке' },
          { emoji: '🎥', name: 'Anime үзэх', value: 'Anime үзнэ' },
        ],
      },
      {
        emoji: '⏰',
        title: 'Хэдэн цагт?',
        key: 'time',
        type: 'time',
        multiSelect: false,
        options: [
          { label: '🌸 11:00', value: '11:00' },
          { label: '☀️ 13:00', value: '13:00' },
          { label: '🍰 15:00', value: '15:00' },
          { label: '🌅 17:00', value: '17:00' },
          { label: '🍬 19:00', value: '19:00' },
          { label: '✨ 20:00', value: '20:00' },
        ],
      },
      {
        emoji: '👗',
        title: 'Хувцасны стиль',
        key: 'outfit',
        type: 'grid',
        multiSelect: false,
        options: [
          { emoji: '🌸', name: 'Cute & Pink', value: 'Cute & Pink' },
          { emoji: '🧸', name: 'Cozy hoodie', value: 'Cozy hoodie' },
          { emoji: '👫', name: 'Matching outfit', value: 'Matching outfit' },
          { emoji: '🎀', name: 'Сюрприз!', value: 'Сюрприз' },
        ],
      },
      {
        emoji: '🎁',
        title: 'Бэлэг юу авах вэ?',
        key: 'gift',
        type: 'grid',
        multiSelect: true,
        options: [
          { emoji: '🍫', name: 'Шоколад', value: 'Шоколад' },
          { emoji: '🧸', name: 'Тоглоом', value: 'Тоглоом' },
          { emoji: '🌸', name: 'Цэцэг', value: 'Цэцэг' },
          { emoji: '🎀', name: 'Гоёл чимэглэл', value: 'Гоёл чимэглэл' },
          { emoji: '🧁', name: 'Бялуу', value: 'Бялуу' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз бэлэг' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '🍬', date: 'Эхний уулзалт', caption: 'Анхны чихэрлэг мөч 🧁' },
      { type: 'image', src: '', placeholder: '🎀', date: 'Төрсөн өдөр', caption: 'Чамтай хамт тэмдэглэсэн тэр өдөр 🎂' },
      { type: 'video', src: '', placeholder: '🎥', date: 'Дурсамж', caption: 'Инээж байсан тэр мөч 😆' },
      { type: 'image', src: '', placeholder: '🌸', date: 'Date', caption: 'Хамтдаа зугаалсан тэр өдөр 💕' },
      { type: 'image', src: '', placeholder: '🧸', date: 'Cute мөч', caption: 'Чи бол миний хамгийн cute хүн 🥰' },
      { type: 'video', src: '', placeholder: '🎬', date: 'Бидний видео', caption: 'Sweet moments together 🍭' },
    ],
    quotes: [
      'Чи бол миний амьдралын хамгийн амттай хэсэг 🍬',
      'Өдөр бүр чамтай хамт шоколад шиг амттай 🍫',
      'Чи бол миний хамгийн cute хүн, хэзээ ч солигдохгүй 🧸',
      'Хайр гэдэг чамтай хамт инээх тэр мөч 💖',
    ],
  },
]
// ============ 2000s / Y2K ХОСУУД ============
const Y2K_TEMPLATES = [
  {
    id: 'y2k-retro',
    category: 'y2k',
    name: 'Y2K Retro Love 📟',
    desc: '2000 оны ностальги стиль',
    preview: '📟💿',
    theme: 'theme-y2k',
    colors: {
      '--t-primary': '#00d4ff',
      '--t-secondary': '#ff00e5',
      '--t-accent': '#39ff14',
      '--t-accent2': '#ffff00',
      '--t-soft': '#b4f0ff',
      '--t-light': '#ffe6fb',
      '--t-bg': '#050510',
      '--t-bg2': '#0a0a20',
      '--t-glass': 'rgba(0, 212, 255, 0.05)',
      '--t-glass-border': 'rgba(0, 212, 255, 0.18)',
    },
    character: 'retro',
    welcomeEmoji: '📟',
    welcomeTitle: 'Y2K Valentine 💿',
    welcomeSubtitle: '2000 оны стилиар хайраа илэрхийлье\nRetro love never dies 🦋',
    questionText: 'AOL-оос чат ирлээ шүү 📧 Be my Valentine? Ctrl+❤️ дар! 💾',
    loveLetter: {
      enabled: true,
      title: 'E-mail from my heart 📧',
      content: 'Subject: I ❤️ U\n\nHi babe! 🦋\n\nЧамд захидал бичих гэж хөгжимтэй MySpace маань нээгээд суулаа... Чи бол миний AIM buddy list-ийн #1. Nokia-гоороо "I miss u" гэж бичих бүрт зүрх минь MSN Messenger-ийн nudge шиг чичирдэг... 📟💕\n\nBe my Valentine? Y/N\n\nxoxo 💋',
    },
    steps: [
      {
        emoji: '💿', title: 'Хаана hangout хийх вэ?', key: 'place', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🎧', name: 'CD дэлгүүр', desc: 'Хөгжимийн дэлгүүр хэсье', value: 'CD дэлгүүр' },
          { emoji: '🎬', name: 'Blockbuster кино', desc: '2000s кино үзье', value: 'Кино' },
          { emoji: '🛼', name: 'Roller skating', desc: 'Дугуйтай тэшүүр', value: 'Roller skating' },
          { emoji: '🍔', name: 'Diner', desc: 'Retro хоолны газар', value: 'Diner' },
          { emoji: '🎮', name: 'Arcade', desc: 'Тоглоомын газар', value: 'Arcade' },
          { emoji: '🏠', name: 'Гэрээр', desc: 'DVD movie night', value: 'DVD night' },
        ],
      },
      {
        emoji: '📀', title: 'Юу хийх вэ?', key: 'activity', type: 'grid', multiSelect: true,
        options: [
          { emoji: '🎵', name: 'Mix CD хийх', value: 'Mix CD хийнэ' },
          { emoji: '📸', name: 'Photo booth', value: 'Photo booth' },
          { emoji: '🎮', name: 'Retro тоглоом', value: 'Retro тоглоом' },
          { emoji: '💌', name: 'Гар захидал', value: 'Гар захидал бичнэ' },
          { emoji: '📞', name: 'Long call', value: 'Удаан утасдана' },
          { emoji: '🛼', name: 'Skating', value: 'Тэшүүр тэшнэ' },
        ],
      },
      {
        emoji: '⏰', title: 'Хэдэн цагт?', key: 'time', type: 'time', multiSelect: false,
        options: [
          { label: '📺 14:00', value: '14:00' },
          { label: '🌅 16:00', value: '16:00' },
          { label: '🌆 18:00', value: '18:00' },
          { label: '📟 20:00', value: '20:00' },
          { label: '🌙 22:00', value: '22:00' },
        ],
      },
      {
        emoji: '👗', title: 'Y2K Style', key: 'outfit', type: 'grid', multiSelect: false,
        options: [
          { emoji: '🦋', name: 'Y2K Glam', value: 'Y2K Glam' },
          { emoji: '👖', name: 'Low-rise & crop', value: 'Low-rise & crop top' },
          { emoji: '🧢', name: 'Sporty', value: 'Sporty' },
          { emoji: '💿', name: 'Сюрприз!', value: 'Сюрприз' },
        ],
      },
      {
        emoji: '🎁', title: 'Бэлэг', key: 'gift', type: 'grid', multiSelect: true,
        options: [
          { emoji: '💿', name: 'Mix CD', value: 'Mix CD' },
          { emoji: '📸', name: 'Polaroid зураг', value: 'Polaroid зураг' },
          { emoji: '📝', name: 'Гар захидал', value: 'Гар захидал' },
          { emoji: '🧸', name: 'Тоглоом баавгай', value: 'Тоглоом баавгай' },
          { emoji: '🦋', name: 'Butterfly зүүлт', value: 'Butterfly зүүлт' },
          { emoji: '🎁', name: 'Сюрприз', value: 'Сюрприз бэлэг' },
        ],
      },
    ],
    memories: [
      { type: 'image', src: '', placeholder: '📟', date: 'First beep', caption: 'Анхны пэйжер мессеж 📟💕' },
      { type: 'image', src: '', placeholder: '💿', date: 'Mix tape', caption: 'Чамд зориулсан Mix CD 🎵' },
      { type: 'image', src: '', placeholder: '📸', date: 'Polaroid', caption: 'Photo booth дурсамж ✨' },
      { type: 'image', src: '', placeholder: '🦋', date: '2000s vibes', caption: 'Butterfly clips & frosted tips 🦋' },
      { type: 'video', src: '', placeholder: '📺', date: 'Movie night', caption: 'DVD movie night хамтдаа 🎬' },
    ],
    quotes: [
      'U R the 1 4 me, чамайг хайрлаж байна 4ever 📟💕',
      'MSN-д online гарахыг чинь хүлээдэг шиг чамайг хүлээнэ 💻',
      'Retro хайр бидний хайр шиг хэзээ ч хуучрахгүй 💿',
      'Чамд зориулсан Mix CD дээр бүх дуу хайрын дуу 🎵',
    ],
  },
]

// ============ EXPORT ============
export const CATEGORIES_CONFIG = {
  crush: CRUSH_TEMPLATES,
  'new-couple': NEW_COUPLE_TEMPLATES,
  'long-term': LONG_TERM_TEMPLATES,
  y2k: Y2K_TEMPLATES,
}

export function getTemplatesByCategory(categoryId) {
  return CATEGORIES_CONFIG[categoryId] || []
}

export function getAllTemplates() {
  return Object.values(CATEGORIES_CONFIG).flat()
}

// Backward compatibility
export const TEMPLATES = getAllTemplates()